nuevos actualizadores de publons y scholar

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -7,7 +7,7 @@
 SRC_BRANCH="master"
 DEPLOY_BRANCH="gh-pages"
 
-USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH]"
+USAGE_MSG="usage: deploy [-h|--help] [-u|--user] [-s|--src SRC_BRANCH] [-d|--deploy DEPLOY_BRANCH] [--verbose] [--no-push]"
 
 while [[ $# > 0 ]]; do
     key="$1"
@@ -20,7 +20,6 @@ while [[ $# > 0 ]]; do
         -u|--user)
         SRC_BRANCH="source"
         DEPLOY_BRANCH="master"
-        shift
         ;;
         -s|--src)
         SRC_BRANCH="$2"
@@ -30,10 +29,16 @@ while [[ $# > 0 ]]; do
         DEPLOY_BRANCH="$2"
         shift
         ;;
+        --verbose)
+        set -x
+        ;;
+        --no-push)
+        NO_PUSH="--no-push"
+        ;;
         *)
-        echo "Option $1 is unknown."
-        echo $USAGE_MSG
-        exit 0
+        echo "Option $1 is unknown." >&2
+        echo $USAGE_MSG >&2
+        exit 1
         ;;
     esac
     shift
@@ -42,20 +47,18 @@ done
 # Exit if any subcommand fails
 set -e
 
-# actualizar valores desde publons
-#echo "Downloading data from publons"
-#sh bin/publons
-##echo "Downloading data from Google Scholar"
-##numberCitations=$(python3 bin/scholar | grep citedby\': | sed 's/[^0-9]*//g')
-##hindex=$(python3 bin/scholar | grep hindex\': | sed 's/[^0-9]*//g')
-##sed -i 's/^number_cites.*$/number_cites: '"${numberCitations}"'/g' _config.yml
-##sed -i 's/^hindex.*$/hindex: '"${hindex}"'/g' _config.yml
-#git add _config.yml
-##git commit --allow-empty -m "updated from publons and scholar"
-#git commit --allow-empty -m "updated from publons"
-#git push -f -q origin source
+# Update Publons and Scholar data in '_config.yml' file.
+echo "Downloading data from Publons."
+sh bin/publons
+echo "Downloading data from Google Scholar."
+sh bin/scholar
 
-#echo "Done!"
+git add _config.yml
+git commit --allow-empty --message "Updated data from Publons and Scholar"
+git push --force --quiet origin source
+
+echo "Done!"
+
 
 echo "Deploying..."
 echo "Source branch: $SRC_BRANCH"
@@ -73,6 +76,15 @@ if ! git diff-index --quiet HEAD --; then
     echo "Changes to the following files are uncommitted:"
     git diff-index --name-only HEAD --
     echo "Please commit the changes before proceeding."
+    echo "Aborting."
+    [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
+fi
+
+# Check if there are any untracked files
+if ! test -z "$(git ls-files --exclude-standard --others)"; then
+    echo "There are untracked files:"
+    git ls-files --exclude-standard --others
+    echo "Please commit those files or stash them before proceeding."
     echo "Aborting."
     [[ "$0" = "$BASH_SOURCE" ]] && exit 1 || return 1
 fi
@@ -103,7 +115,7 @@ rm -R _site/
 # Push to DEPLOY_BRANCH
 git add -fA
 git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci skip]"
-git push -f -q origin $DEPLOY_BRANCH
+[[ ${NO_PUSH} ]] || git push -f -q origin $DEPLOY_BRANCH
 
 # Move back to SRC_BRANCH
 git checkout $SRC_BRANCH
diff --git a/bin/publons b/bin/publons
--- a/bin/publons
+++ b/bin/publons
@@ -1,15 +1,43 @@
-# se descargan los datos
-datos=$(curl -X GET https://publons.com/api/v2/academic/0000-0003-0413-5677/ -H "Authorization: Token ace7d54c7af9098e413f12c2867cd13a24adfef6" -H "Content-Type: application/json")
+#!/bin/sh
+
+readonly PUBLONS_URL="https://publons.com/api/v2/academic/0000-0003-0413-5677/"
+readonly TOKEN="ace7d54c7af9098e413f12c2867cd13a24adfef6"
+
+
+[ -z "$(command -v curl)" ] && echo "You need to install curl." && exit 1
+[ -z "$(command -v jq  )" ] && echo "You need to install jq."   && exit 1
+
+# Download data
+data="$(curl      "${PUBLONS_URL}"                    \
+        --request  GET                                \
+        --header  "Authorization: Token ${TOKEN}"     \
+        --header  "Content-Type:  application/json")"
+
+# sed and mv commands are used because sed -i (--in-place) option is not portable between GNU and BSD/macOS. More info in:
+# https://stackoverflow.com/questions/16745988/sed-command-with-i-option-in-place-editing-works-fine-on-ubuntu-but-not-mac
 
 # se extraen numero de revisiones y se cambia en el fichero
-numberReviews=$(echo $datos | jq '.reviews.pre.count')
-sed -i 's/^number_reviews.*$/number_reviews: '"${numberReviews}"'/g' _config.yml
+numberReviews="$(echo "${data}" | jq '.reviews.pre.count')"
+if [ -z "${numberReviews}" ]; then
+    echo "Number of reviews could not be retrieved from Publons."
+else
+    sed --expression='s/^publons_number_reviews.*$/publons_number_reviews: '"${numberReviews}"'/g' _config.yml > _config.yml.bak \
+        && mv _config.yml.bak _config.yml
+fi
 
 # se extraen numero de trabajos como editor y se cambia en el fichero
-numberEditor=$(echo $datos | jq '.handling_editor_records.count')
-sed -i 's/^number_editor.*$/number_editor: '"${numberEditor}"'/g' _config.yml
+numberEditor="$(echo "${data}" | jq '.handling_editor_records.count')"
+if [ -z "${numberEditor}" ]; then
+    echo "Number of editions could not be retrieved from Publons."
+else
+    sed --expression='s/^publons_number_editor.*$/publons_number_editor: '"${numberEditor}"'/g' _config.yml > _config.yml.bak \
+        && mv _config.yml.bak _config.yml
+fi
 
-# se cambia la fecha de ultima actualizacion
-lastUpdate=$(date +"%Y-%m-%d")
-sed -i 's/^last_updated.*$/last_updated: '"${lastUpdate}"'/g' _config.yml
+# Update 'publons_last_updated'.
+lastUpdate="$(date +"%Y-%m-%d")"
+sed --expression='s/^publons_last_updated.*$/publons_last_updated: '"${lastUpdate}"'/g' _config.yml > _config.yml.bak \
+    && mv _config.yml.bak _config.yml
 
+sed --expression='s/^web_last_updated.*$/web_last_updated: '"${lastUpdate}"'/g' _config.yml > _config.yml.bak \
+    && mv _config.yml.bak _config.yml
